package com.example.currency_converter_android_app;

import java.util.HashMap;
import java.util.Map;

public class CurrencyCodeAndName {

    private static final Map<String, String> currencyMap = new HashMap<>();

    static {
        currencyMap.put("AED", "UAE Dirham");
        currencyMap.put("AFN", "Afghan Afghani");
        currencyMap.put("ALL", "Albanian Lek");
        currencyMap.put("AMD", "Armenian Dram");
        currencyMap.put("ANG", "Netherlands Antillian Guilder");
        currencyMap.put("AOA", "Angolan Kwanza");
        currencyMap.put("ARS", "Argentine Peso");
        currencyMap.put("AUD", "Australian Dollar");
        currencyMap.put("AWG", "Aruban Florin");
        currencyMap.put("AZN", "Azerbaijani Manat");
        currencyMap.put("BAM", "Bosnia and Herzegovina Convertible Mark");
        currencyMap.put("BBD", "Barbados Dollar");
        currencyMap.put("BDT", "Bangladeshi Taka");
        currencyMap.put("BGN", "Bulgarian Lev");
        currencyMap.put("BHD", "Bahraini Dinar");
        currencyMap.put("BIF", "Burundian Franc");
        currencyMap.put("BMD", "Bermudian Dollar");
        currencyMap.put("BND", "Brunei Dollar");
        currencyMap.put("BOB", "Bolivian Boliviano");
        currencyMap.put("BRL", "Brazilian Real");
        currencyMap.put("BSD", "Bahamian Dollar");
        currencyMap.put("BTN", "Bhutanese Ngultrum");
        currencyMap.put("BWP", "Botswana Pula");
        currencyMap.put("BYN", "Belarusian Ruble");
        currencyMap.put("BZD", "Belize Dollar");
        currencyMap.put("CAD", "Canadian Dollar");
        currencyMap.put("CDF", "Congolese Franc");
        currencyMap.put("CHF", "Swiss Franc");
        currencyMap.put("CLP", "Chilean Peso");
        currencyMap.put("CNY", "Chinese Renminbi");
        currencyMap.put("COP", "Colombian Peso");
        currencyMap.put("CRC", "Costa Rican Colon");
        currencyMap.put("CUP", "Cuban Peso");
        currencyMap.put("CVE", "Cape Verdean Escudo");
        currencyMap.put("CZK", "Czech Koruna");
        currencyMap.put("DJF", "Djiboutian Franc");
        currencyMap.put("DKK", "Danish Krone");
        currencyMap.put("DOP", "Dominican Peso");
        currencyMap.put("DZD", "Algerian Dinar");
        currencyMap.put("EGP", "Egyptian Pound");
        currencyMap.put("ERN", "Eritrean Nakfa");
        currencyMap.put("ETB", "Ethiopian Birr");
        currencyMap.put("EUR", "Euro");
        currencyMap.put("FJD", "Fiji Dollar");
        currencyMap.put("FKP", "Falkland Islands Pound");
        currencyMap.put("FOK", "Faroese Króna");
        currencyMap.put("GBP", "Pound Sterling");
        currencyMap.put("GEL", "Georgian Lari");
        currencyMap.put("GGP", "Guernsey Pound");
        currencyMap.put("GHS", "Ghanaian Cedi");
        currencyMap.put("GIP", "Gibraltar Pound");
        currencyMap.put("GMD", "Gambian Dalasi");
        currencyMap.put("GNF", "Guinean Franc");
        currencyMap.put("GTQ", "Guatemalan Quetzal");
        currencyMap.put("GYD", "Guyanese Dollar");
        currencyMap.put("HKD", "Hong Kong Dollar");
        currencyMap.put("HNL", "Honduran Lempira");
        currencyMap.put("HRK", "Croatian Kuna");
        currencyMap.put("HTG", "Haitian Gourde");
        currencyMap.put("HUF", "Hungarian Forint");
        currencyMap.put("IDR", "Indonesian Rupiah");
        currencyMap.put("ILS", "Israeli New Shekel");
        currencyMap.put("IMP", "Manx Pound");
        currencyMap.put("INR", "Indian Rupee");
        currencyMap.put("IQD", "Iraqi Dinar");
        currencyMap.put("IRR", "Iranian Rial");
        currencyMap.put("ISK", "Icelandic Króna");
        currencyMap.put("JEP", "Jersey Pound");
        currencyMap.put("JMD", "Jamaican Dollar");
        currencyMap.put("JOD", "Jordanian Dinar");
        currencyMap.put("JPY", "Japanese Yen");
        currencyMap.put("KES", "Kenyan Shilling");
        currencyMap.put("KGS", "Kyrgyzstani Som");
        currencyMap.put("KHR", "Cambodian Riel");
        currencyMap.put("KID", "Kiribati Dollar");
        currencyMap.put("KMF", "Comorian Franc");
        currencyMap.put("KRW", "South Korean Won");
        currencyMap.put("KWD", "Kuwaiti Dinar");
        currencyMap.put("KYD", "Cayman Islands Dollar");
        currencyMap.put("KZT", "Kazakhstani Tenge");
        currencyMap.put("LAK", "Lao Kip");
        currencyMap.put("LBP", "Lebanese Pound");
        currencyMap.put("LKR", "Sri Lanka Rupee");
        currencyMap.put("LRD", "Liberian Dollar");
        currencyMap.put("LSL", "Lesotho Loti");
        currencyMap.put("LYD", "Libyan Dinar");
        currencyMap.put("MAD", "Moroccan Dirham");
        currencyMap.put("MDL", "Moldovan Leu");
        currencyMap.put("MGA", "Malagasy Ariary");
        currencyMap.put("MKD", "Macedonian Denar");
        currencyMap.put("MMK", "Burmese Kyat");
        currencyMap.put("MNT", "Mongolian Tögrög");
        currencyMap.put("MOP", "Macanese Pataca");
        currencyMap.put("MRU", "Mauritanian Ouguiya");
        currencyMap.put("MUR", "Mauritian Rupee");
        currencyMap.put("MVR", "Maldivian Rufiyaa");
        currencyMap.put("MWK", "Malawian Kwacha");
        currencyMap.put("MXN", "Mexican Peso");
        currencyMap.put("MYR", "Malaysian Ringgit");
        currencyMap.put("MZN", "Mozambican Metical");
        currencyMap.put("NAD", "Namibian Dollar");
        currencyMap.put("NGN", "Nigerian Naira");
        currencyMap.put("NIO", "Nicaraguan Córdoba");
        currencyMap.put("NOK", "Norwegian Krone");
        currencyMap.put("NPR", "Nepalese Rupee");
        currencyMap.put("NZD", "New Zealand Dollar");
        currencyMap.put("OMR", "Omani Rial");
        currencyMap.put("PAB", "Panamanian Balboa");
        currencyMap.put("PEN", "Peruvian Sol");
        currencyMap.put("PGK", "Papua New Guinean Kina");
        currencyMap.put("PHP", "Philippine Peso");
        currencyMap.put("PKR", "Pakistani Rupee");
        currencyMap.put("PLN", "Polish Złoty");
        currencyMap.put("PYG", "Paraguayan Guaraní");
        currencyMap.put("QAR", "Qatari Riyal");
        currencyMap.put("RON", "Romanian Leu");
        currencyMap.put("RSD", "Serbian Dinar");
        currencyMap.put("RUB", "Russian Ruble");
        currencyMap.put("RWF", "Rwandan Franc");
        currencyMap.put("SAR", "Saudi Riyal");
        currencyMap.put("SBD", "Solomon Islands Dollar");
        currencyMap.put("SCR", "Seychellois Rupee");
        currencyMap.put("SDG", "Sudanese Pound");
        currencyMap.put("SEK", "Swedish Krona");
        currencyMap.put("SGD", "Singapore Dollar");
        currencyMap.put("SHP", "Saint Helena Pound");
        currencyMap.put("SLE", "Sierra Leonean Leone");
        currencyMap.put("SLL", "Sierra Leonean Leone");
        currencyMap.put("SOS", "Somali Shilling");
        currencyMap.put("SRD", "Surinamese Dollar");
        currencyMap.put("SSP", "South Sudanese Pound");
        currencyMap.put("STN", "São Tomé and Príncipe Dobra");
        currencyMap.put("SYP", "Syrian Pound");
        currencyMap.put("SZL", "Eswatini Lilangeni");
        currencyMap.put("THB", "Thai Baht");
        currencyMap.put("TJS", "Tajikistani Somoni");
        currencyMap.put("TMT", "Turkmenistan Manat");
        currencyMap.put("TND", "Tunisian Dinar");
        currencyMap.put("TOP", "Tongan Paʻanga");
        currencyMap.put("TRY", "Turkish Lira");
        currencyMap.put("TTD", "Trinidad and Tobago Dollar");
        currencyMap.put("TWD", "New Taiwan Dollar");
        currencyMap.put("TZS", "Tanzanian Shilling");
        currencyMap.put("UAH", "Ukrainian Hryvnia");
        currencyMap.put("UGX", "Ugandan Shilling");
        currencyMap.put("USD", "United States Dollar");
        currencyMap.put("UYU", "Uruguayan Peso");
        currencyMap.put("UZS", "Uzbekistani Som");
        currencyMap.put("VEF", "Venezuelan Bolívar");
        currencyMap.put("VND", "Vietnamese Dong");
        currencyMap.put("VUV", "Vanuatu Vatu");
        currencyMap.put("WST", "Samoan Tala");
        currencyMap.put("XAF", "Central African CFA Franc");
        currencyMap.put("XCD", "East Caribbean Dollar");
        currencyMap.put("XOF", "West African CFA Franc");
        currencyMap.put("XPF", "CFP Franc");
        currencyMap.put("YER", "Yemeni Rial");
        currencyMap.put("ZAR", "South African Rand");
        currencyMap.put("ZMW", "Zambian Kwacha");
        currencyMap.put("ZWL", "Zimbabwean Dollar");
    }

    public static String findCurrencyName(String code) {
        return currencyMap.getOrDefault(code, "Currency code not found");
    }
}